# version: "3"

services:
  app:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: "./"
        target: "/app"
  nginx:
    image: nginx:1.19.6
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./containers/nginx/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./json-tool-web/dist:/var/www/html